let ignore_files = [
  "Actionscript.gitignore"; "Ada.gitignore"; "Agda.gitignore"; "Android.gitignore"; "AppEngine.gitignore";
  "AppceleratorTitanium.gitignore"; "ArchLinuxPackages.gitignore"; "Autotools.gitignore";
  "C++.gitignore"; "C.gitignore"; "CFWheels.gitignore"; "CMake.gitignore"; "CUDA.gitignore";
  "CakePHP.gitignore"; "ChefCookbook.gitignore"; "Clojure.gitignore"; "CodeIgniter.gitignore"; "CommonLisp.gitignore";
  "Composer.gitignore"; "Concrete5.gitignore"; "Coq.gitignore"; "CraftCMS.gitignore";
  "D.gitignore"; "DM.gitignore"; "Dart.gitignore"; "Delphi.gitignore"; "Drupal.gitignore";
  "EPiServer.gitignore"; "Eagle.gitignore"; "Elisp.gitignore"; "Elixir.gitignore"; "Elm.gitignore";
  "Erlang.gitignore"; "ExpressionEngine.gitignore"; "ExtJs.gitignore";
  "Fancy.gitignore"; "Finale.gitignore"; "ForceDotCom.gitignore"; "Fortran.gitignore"; "FuelPHP.gitignore";
  "GWT.gitignore"; "Gcov.gitignore"; "GitBook.gitignore"; "Go.gitignore"; "Gradle.gitignore";
  "Grails.gitignore";
  "Haskell.gitignore";
  "IGORPro.gitignore"; "Idris.gitignore";
  "Java.gitignore"; "Jboss.gitignore"; "Jekyll.gitignore"; "Joomla.gitignore"; "Julia.gitignore";
  "KiCad.gitignore"; "Kohana.gitignore";
  "LabVIEW.gitignore"; "Laravel.gitignore"; "Leiningen.gitignore"; "LemonStand.gitignore"; "Lilypond.gitignore";
  "Lithium.gitignore"; "Lua.gitignore";
  "Magento.gitignore"; "Maven.gitignore"; "Mercury.gitignore"; "MetaProgrammingSystem.gitignore";
  "Nanoc.gitignore"; "Nim.gitignore"; "Node.gitignore";
  "OCaml.gitignore"; "Objective-C.gitignore"; "Opa.gitignore"; "OpenCart.gitignore"; "OracleForms.gitignore";
  "Packer.gitignore"; "Perl.gitignore"; "Phalcon.gitignore"; "PlayFramework.gitignore"; "Plone.gitignore";
  "Prestashop.gitignore"; "Processing.gitignore"; "Python.gitignore";
  "Qooxdoo.gitignore"; "Qt.gitignore";
  "R.gitignore"; "ROS.gitignore"; "Rails.gitignore"; "RhodesRhomobile.gitignore"; "Ruby.gitignore";
  "Rust.gitignore";
  "SCons.gitignore"; "Sass.gitignore"; "Scala.gitignore"; "Scheme.gitignore"; "Scrivener.gitignore";
  "Sdcc.gitignore"; "SeamGen.gitignore"; "SketchUp.gitignore"; "Smalltalk.gitignore"; "Stella.gitignore";
  "SugarCRM.gitignore"; "Swift.gitignore"; "Symfony.gitignore"; "SymphonyCMS.gitignore";
  "TeX.gitignore"; "Terraform.gitignore"; "Textpattern.gitignore"; "TurboGears2.gitignore"; "Typo3.gitignore";
  "Umbraco.gitignore"; "Unity.gitignore"; "UnrealEngine.gitignore";
  "VVVV.gitignore"; "VisualStudio.gitignore";
  "Waf.gitignore"; "WordPress.gitignore";
  "Xojo.gitignore";
  "Yeoman.gitignore"; "Yii.gitignore";
  "ZendFramework.gitignore"; "Zephir.gitignore"]

let extensions = [
  ("Agda.gitignore", ["agda"]);
  ("Android.gitignore", ["java"]);
  ("C.gitignore", ["c"; "h"]);
  ("C++.gitignore", ["cpp"; "hpp"]);
  ("CakePHP.gitignore", ["php"]);
  ("CommonLisp.gitignore", ["cl"]);
  ("Drupal.gitignore", ["php"; "twig"]);
  ("Elisp.gitignore", ["el"]);
  ("Elixir.gitignore", ["ex"]);
  ("Elm.gitignore", ["elm"]);
  ("Erlang.gitignore", ["erl"]);
  ("FuelPHP.gitignore", ["php"]);
  ("Groovy.gitignore", ["groovy"]);
  ("Haskell.gitignore", ["hs"]);
  ("Idris.gitignore", ["idr"]);
  ("Java.gitignore", ["java"]);
  ("JavaScript.gitignore", ["js"]);
  ("Julia.gitignore", ["julia"]);
  ("Kohana.gitignore", ["php"]);
  ("Leiningen.gitignore", ["clj"; "cljs"; "cljc"]);
  ("Magento.gitignore", ["php"]);
  ("OCaml.gitignore", ["ml"; "mli"]);
  ("Perl.gitignore", ["pl"]);
  ("Prestashop.gitignore", ["php"]);
  ("Python.gitignore", ["py"; "pyc"]);
  ("R.gitignore", ["r"]);
  ("Rails.gitignore", ["rb"; "erb"]);
  ("Ruby.gitignore", ["rb"; "erb"]);
  ("Rust.gitignore", ["rs"]);
  ("Scala.gitignore", ["scala"]);
  ("Scheme.gitignore", ["scheme"]);
  ("TeX.gitignore", ["tex"]);
]
